name: 'Pull Request Approval Tracker'
description: 'Check pull requests for review approval and mark them'
inputs:
  secret_token:
    description: 'Github secret token'
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: tag
  color: gray-dark
